---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ANSIBLE_HOST_KEY_CHECKING: false
    - ansible_stdout_callback: yaml

  environment:
    ANSIBLE_HOST_KEY_CHECKING: false
    ENVIRONMENT: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    TYPEORM_HOST: project3
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: postgres
    TYPEORM_PASSWORD: project3
    TYPEORM_DATABASE: project3

  tasks:

  - name: "update apt packages."
    become: yes
    apt:
      update_cache: yes

  - name: "Update all packages to the latest version"
    become: yes
    apt:
      name: aptitude


  - name: "Install NODEJS"
    become: yes
    shell: |
      curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -

  - name: "Install npm"
    become: yes
    apt:
      name: npm

  - name: "Install tsc"
    become: yes
    npm:
      global: yes
      name: tsc

  - name: "Install concurrently"
    become: yes
    npm:
      global: yes
      name: concurrently

  - name: "Install typescript"
    become: yes
    npm:
      global: yes
      name: typescript

  - name: "Install Pm2"
    become: yes
    npm:
      global: yes
      name: pm2
