---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ANSIBLE_HOST_KEY_CHECKING: false
    ansible_stdout_callback: yaml


  tasks:



  - name: update apt packages
    become: yes
    apt:
      update_cache: yes

  - name: Update all packages to the latest version
    become: yes
    apt:
      name: aptitude

  - name: Install Unzip
    become: yes
    apt:
      name: unzip

  - name: Install NODEJS13 REPO
    shell: |
      curl -sL https://deb.nodesource.com/setup_13.x | sudo bash -
      sudo apt -y install nodejs


  - name: "Install Pm2"
    become: yes
    npm:
      global: yes
      name: pm2
      production: yes
      state: present
