---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml



- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "Install NODEJS"
  become: yes
  apt:
    name: nodejs

- name: "Install npm"
  become: yes
  apt:
    name: npm

- name: "Install Pm2"
  become: yes
  npm:
    global: yes
    name: pm2
