
---

- name: "deploy play."
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ANSIBLE_HOST_KEY_CHECKING: false
    - ansible_stdout_callback: yaml

  environment:
    - ANSIBLE_HOST_KEY_CHECKING: false

  tasks:

  - name: Make Project Folder
    shell: mkdir ~/project3

  - name: Git Checkout
    git:
      repo: https://github.com/Fontaineconsult/UCDOEND_Project3.git
      dest: ~/project3




  - name: Uhgggg
    command: ~/project3
    register: dir_out
    debug: dir_out.stdout_lines

  - name: Uhgggg1111
    command: ~/project3/UCDOEND_Project3
    register: dir_out
    debug: dir_out.stdout_lines

  - name: CD Backend
    shell: cd ~/project3/UCDOEND_Project3/


  - name: CD Take A Look
    shell: ls


  - name: Start Migration
    shell: npm run ~/project3/UCDOEND_Project3/backend/migrations > output.txt

  - name: Test
    shell: ls ~/project3/UCDOEND_Project3/.circleci/ansible/roles/deploy-backend/files

  - name: Test1
    shell: cat ~/project3/UCDOEND_Project3/.circleci/ansible/roles/deploy-backend/files/wid.txt

  - name: Save ouput to memstash if success
    shell: >
      if grep "has been executed successfully" output.txt; |
      then curl -H "Content-Type: text/plain" -H "token: 7cb66ce8-9b24-4bbd-9b69-31b5ca339fc1" --request PUT --data "0" https://api.memstash.io/values/$(< .circleci/ansible/roles/deploy-backend/files/wid.txt); fi

  - name: Save ouput to memstash if fail
    shell: >
      if ! grep "has been executed successfully" output.txt; |
      then curl -H "Content-Type: text/plain" -H "token: 7cb66ce8-9b24-4bbd-9b69-31b5ca339fc1" --request PUT --data "1" https://api.memstash.io/values/$(< .circleci/ansible/roles/deploy-backend/files/wid.txt); fi




