---
- name: "configuration play."
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  tasks:


    - name: Move Files
      copy:
        src: dist.zip
        dest: ~/backend/



    - name: Take a look
      shell:
        ls backend

    - name: Unzip
      shell:
        cd backend
        mkdir dist
        unzip dist.zip -d ./dist


    - name: Start PM2
      environment:
        ANSIBLE_HOST_KEY_CHECKING: false
        ENVIRONMENT: production
        TYPEORM_CONNECTION: postgres
        TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
        TYPEORM_HOST: project3.cmill571hyhm.us-west-2.rds.amazonaws.com
        TYPEORM_PORT: 5432
        TYPEORM_USERNAME: postgres
        TYPEORM_PASSWORD: project3
        TYPEORM_DATABASE: postgres

      shell:
        cd backend/dist
        pm2 start main.js