---
- name: "configuration play."
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  tasks:

    - name: Move Files
      copy:
        src: "{{ item }}"
        dest: ~/dist
      with_fileglob:
        - dist/*

    - name: Take a look
      shell:
        ls

