---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  tasks:

    - name: Git Checkout
      git:
        repo: https://github.com/Fontaineconsult/UCDOEND_Project3.git
        dest: ~/

    - name: CD Into Backend
      command: cd backend

    - name: Take a Look
      command: ls

    - name: Start Migration
      command: npm run migrations > output.txt

    - name: Save ouput to memstash if success
      shell: if grep -q "has been executed successfully" output.txt; then curl -H "Content-Type: text/plain" -H "token: ef8d48b8-e227-4017-b947-1a2329902938" --request PUT --data "0" https://api.memstash.io/values/$(< wid.txt); fi

    - name: Save ouput to memstash if fail
      shell: if ! grep -q "has been executed successfully" output.txt; then curl -H "Content-Type: text/plain" -H "token: ef8d48b8-e227-4017-b947-1a2329902938" --request PUT --data "1" https://api.memstash.io/values/$(< wid.txt); fi




